databases:
  -name: broker
   databaseName: broker
   user: broker

services:
  -type: web
   name: broker
   runtime: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn broker.wsgi"
   envVars:
    -key: DATABASE_URL
      fromDatabase:
       name: broker
       property: connectionString
    -key: SECRET_KEY
     generateValue: true
    -key: WEB_CONCURRENCY
     value: 4
    
